# Generated by Django 4.2.6 on 2023-10-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PieceInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('old_content_link', models.URLField(blank=True, null=True)),
                ('include_data', models.CharField(blank=True, max_length=255, null=True)),
                ('csvs', models.FileField(blank=True, null=True, upload_to='csvs/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinner.project')),
            ],
        ),
        migrations.CreateModel(
            name='PieceBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.TextField()),
                ('research', models.TextField()),
                ('piece_inputs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinner.pieceinputs')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('piece_inputs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinner.pieceinputs')),
            ],
        ),
    ]
